/**
 * Call — Type definitions for voice call records and live call state.
 *
 * Used across the frontend (call history, live call UI) and backend
 * (VAPI webhook payloads, database models).
 */

// ─── Enums ──────────────────────────────────────────────────────────

/** Lifecycle status of a call from initiation to completion. */
export enum CallStatus {
  INITIATED = "INITIATED",
  RINGING = "RINGING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  MISSED = "MISSED",
  VOICEMAIL = "VOICEMAIL",
}

/** Whether the call was placed by the agent or received from outside. */
export enum CallDirection {
  INBOUND = "INBOUND",
  OUTBOUND = "OUTBOUND",
}

/** Final outcome of a completed call, used for analytics and reporting. */
export enum CallOutcome {
  CONVERTED = "CONVERTED",
  ANSWERED = "ANSWERED",
  MISSED = "MISSED",
  VOICEMAIL = "VOICEMAIL",
  FAILED = "FAILED",
}

// ─── Interfaces ─────────────────────────────────────────────────────

/** Persistent call record stored in the database. */
export interface ICall {
  id: string;
  agentId: string;
  userId: string;
  contactName: string;
  contactNumber: string;
  direction: CallDirection;
  status: CallStatus;
  outcome?: CallOutcome;
  /** Call duration in seconds. */
  duration?: number;
  /** Full transcript generated by VAPI after the call ends. */
  transcript?: string;
  /** URL to the call recording audio file. */
  recordingUrl?: string;
  startedAt?: Date;
  endedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

/** Live call state tracked in the frontend store during an active call. */
export interface IActiveCall {
  callId: string;
  contactName: string;
  contactNumber: string;
  direction: CallDirection;
  status: CallStatus;
  startedAt: Date;
  /** Elapsed time in seconds, updated by a timer on the frontend. */
  durationSeconds: number;
}
